---
- name: Create directories for SAP NetWeaver Application Server kit on target
  file:
    path: "{{ nwinst_dir }}"
    state: directory
    mode: 0777
  loop: "{{ nwinst_dirs }}"
  loop_control:
    loop_var: nwinst_dir

- name: Copy SAP NetWeaver Application Server kit to /usr/sap/trans/kit
  copy:
    src: "{{ kit_item.nwapp_src }}"
    dest: "{{ kit_item.nwapp_dest }}"
    owner: root
    group: root
    mode: 0777
  loop: "{{ nwapp_kits }}"
  loop_control:
    loop_var: kit_item

- name: Check if HDBClient archive content was already extracted
  stat:
    path: "{{ nwapp_kit }}/hdbclient/hdbclientreg"
  register: hdbclientfile_status

- name: Extract HDBClient archive
  command: "{{ nwapp_kit }}/sapcar -xf {{ nwapp_kit }}/hdbclient.sar -R {{ nwapp_kit }}/hdbclient"
  when: not hdbclientfile_status.stat.exists

- name: Check if Export archive content was already extracted
  stat:
    path: "{{ nwapp_kit }}/export/DATA_UNITS/LABELIDX.ASC"
  register: expfile_status

- name: Extract the export ZIP file to target
  unarchive:
    src: "{{ nwapp_kit }}/export/{{ kit_nwhana_export_file.split('/')[-1] }}"
    dest: "{{ nwapp_kit }}/export/"
    remote_src: yes
  when: not expfile_status.stat.exists

- name: Check if SWPM archive content was already extracted
  stat:
    path: "{{ nwapp_kit }}/swpm/sapinst"
  register: file_status

- name: Extract SWPM archive
  command: "{{ nwapp_kit }}/sapcar -xf {{ nwapp_kit }}/swpm.sar -R {{ nwapp_kit }}/swpm"
  when: not file_status.stat.exists
...
