---
- name: Select HANA profile for saptune
  command: /usr/sbin/saptune solution apply HANA

- name: Start and enable saptune service
  service:
    name: saptune
    state: started
    enabled: yes
...